seed: 2024
mode: test
train_img_dir: ./data/数据集/train
train_mask_dir: ./data/数据集/train_mask
val_img_dir: ./data/数据集/val
val_mask_dir: ./data/数据集/val_mask
test_img_dir: ./data/数据集/test
test_mask_dir: ./data/数据集/test_mask
tensorboard_dir: ./tensorboard
log_dir: ./log
output_dir: ./output
checkpoints_dir: ./checkpoints
test_checkpoint: ./checkpoints/best_unet_checkpoint.pt
log_step: 5

learning_rate: 0.0001
batch_size: 4
epochs: 100

