seed: 2024
mode: train
train_dir: ./data/数据集/train_val
lable_file: ./data/数据集/train_val/lables.csv
tensorboard_dir: ./tensorboard
log_dir: ./log
output_dir: ./output
checkpoints_dir: ./checkpoints
log_step: 5

learning_rate: 0.0001
train_size: 0.8
batch_size: 4
epochs: 20

